name: Street Zen
favicon: null
layout_spectrum: 0.08244178653694689
typography_spectrum: 0.23700105608440936
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#424249'
    - '#4285f4'
    - '#ea4335'
    - '#fbbc05'
  brandStrength: 0.5
  lightness: 0.4566270981449634
  saturation: 0.8793921407777816
  rhythmicContrast: 0.33390278089791536
purpose: []
